

deployments:
  - deleteObjects:
      - kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
      - kind: DaemonSet
        namespace: kube-system
        name: aws-node
  - barrier: true
  - path: cilium
  - path: metallb
  - barrier: true
  - path: metallb-address-pools
  - path: cert-manager
  #- path: flux-kluctl-controller
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      #ref: v2.20.3
    vars:
      - values:
          args:
            controller_version: v2.21.0-devel
            #controller_version: v2.21.0-snapshot-arm64
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/webui
      #ref: v2.20.3
    vars:
      - values:
          args:
            kluctl_version: v2.21.0-devel
            #controller_version: v2.21.0-snapshot-arm64
  - barrier: true
  - path: template-controller
  - path: argocd
