

deployments:
  - deleteObjects:
      - kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
      - kind: DaemonSet
        namespace: kube-system
        name: aws-node
  - barrier: true
  - path: cilium
  #- path: metallb
  - barrier: true
  #- path: metallb-address-pools
  - path: cert-manager
  - path: external-dns
    when: target.name == "eks"
  #- path: flux-kluctl-controller
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      ref: main
    vars:
      - values:
          args:
            kluctl_version: {{ args.kluctl_version }}
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/webui
      ref: main
    vars:
      - values:
          args:
            kluctl_version: {{ args.kluctl_version }}
            webui_args:
              - --auth-oidc-issuer-url=https://dev-jz08amaw1l857mu3.us.auth0.com/
              - --auth-oidc-client-id=7AitfQAj74oQ0EXJVZX7QrmEHSyxnvMK
              - --auth-oidc-scope=openid
              - --auth-oidc-scope=profile
              - --auth-oidc-scope=email
              - --auth-oidc-scope=https://kluctl.io/roles
              - --auth-oidc-redirect-url=https://webui.kluctl-demo.kluctl.io/auth/callback
              - --auth-oidc-group-claim=https://kluctl.io/roles
              - --auth-oidc-admins-group=kluctl-admins
              - --auth-oidc-viewers-group=kluctl-viewers
  - barrier: true
  - path: cluster-issuer
  - path: template-controller
  - path: argocd
  - barrier: true
  - path: kluctl-webui-ingress
    when: target.name == "eks"
