

deployments:
  - deleteObjects:
      - kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
      - kind: DaemonSet
        namespace: kube-system
        name: aws-node
  - barrier: true
  - path: cilium
  #- path: metallb
  - barrier: true
  #- path: metallb-address-pools
  - path: cert-manager
  - path: external-dns
    when: target.name == "eks"
  #- path: flux-kluctl-controller
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      ref: main
    vars:
      - values:
          args:
            kluctl_version: {{ args.kluctl_version }}
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/webui
      ref: main
    vars:
      - values:
          args:
            kluctl_version: {{ args.kluctl_version }}
            webui_args:
              - --auth-oidc-issuer-url=https://login.microsoftonline.com/b61015d5-2e5a-478c-aafa-10e96c9fc5f7/v2.0
              - --auth-oidc-client-id=ef6df238-47c0-4cf6-8606-b623c4b477a8
              - --auth-oidc-scope=openid
              - --auth-oidc-scope=profile
              - --auth-oidc-scope=email
              - --auth-oidc-redirect-url=https://webui.kluctl-demo.kluctl.io/auth/callback
              - --auth-oidc-group-claim=groups
              - --auth-oidc-admins-group=3131250f-1d8c-4218-bba9-ee29f49948bc
              - --auth-oidc-viewers-group=3131250f-1d8c-4218-bba9-ee29f49948bc
  - barrier: true
  - path: cluster-issuer
  - path: template-controller
  - path: argocd
  - barrier: true
  - path: kluctl-webui-ingress
    when: target.name == "eks"
