

deployments:
  - deleteObjects:
      - kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
      - kind: DaemonSet
        namespace: kube-system
        name: aws-node
  - barrier: true
  - path: cilium
  #- path: metallb
  - barrier: true
  #- path: metallb-address-pools
  - path: cert-manager
  - path: external-dns
  #- path: flux-kluctl-controller
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/controller
      #ref: v2.20.3
    vars:
      - values:
          args:
            controller_version: {{ args.kluctl_version }}
  - git:
      url: https://github.com/kluctl/kluctl.git
      subDir: install/webui
      #ref: v2.20.3
    vars:
      - values:
          args:
            kluctl_version: {{ args.kluctl_version }}
  - barrier: true
  - path: cluster-issuer
  - path: template-controller
  - path: argocd
  - barrier: true
  - path: kluctl-webui-ingress
    when: target.name == "eks"
