# permissions for end users to view kluctldeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kluctldeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: kluctldeployment-viewer-role
rules:
- apiGroups:
  - gitops.kluctl.io
  resources:
  - kluctldeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitops.kluctl.io
  resources:
  - kluctldeployments/status
  verbs:
  - get
